### ISSUE TITLE
UBKG-API: POST endpoints return 500 errors

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/ubkg#55]
example:
concepts/expand

See the [UBKG SmartAPI page](https://smart-api.info/ui/33a83dc8f62b4a9aaecd32a24cb8563c#/default/concepts_expand_post)

{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}

**Comment by AlanSimmons** [comment]
@ChuckKollar, @yuanzhou, @shirey 
Other issues that I noticed while trying to debug this issue using my local clone:

1. When I installed APOC in my local neo4j instance, the 500 server error disappeared. However, I got errors like this when I tried to execute a POST call (via PostMan)

```
[2023-02-21 08:34:59] INFO in _internal:224: 127.0.0.1 - - [21/Feb/2023 08:34:59] "POST /concepts/expand HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/Users/jas971/PycharmProjects/UBKG/API/venv/lib/python3.11/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: concepts_expand_post() missing 1 required positional argument: 'concept_sab_rel_depth'
```

2. The *build-server.sh* file still contained references to ontology-api-spec.yaml instead of ubkg-api-spec.yaml, as well as to hu-bmpa-ontology-api-client. I updated the references and rebuilt my server (build-server.sh -R), but still get the errors.

3. All of the POST calls fail with the same type of error. It looks like the request body is not being passed to the API via the URL for some reason. Something in the API (uswgi?) does not recognize the request body. I copied the example ones from the SmartAPI documentation.
4. It does not help that running build-server.sh appears to overwrite the requirements.txt file in the local repo. The overwriting is somewhere in the workflow. I thought that I had caught all instances of where the build process fetched files from an old Dockerfile and github repo, but maybe not.

**Comment by shirey** [comment]
Closing as unneeded. Will add a GET for now, then refactor the REST client
